'use client'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Brain, Briefcase, FileSearch, Scale, Target, PlayCircle, ArrowRight, Activity, TrendingUp } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export default function DashboardHome() {
  const agents = [
    { title: "Scout Agent", desc: "CV vs Job Match", icon: FileSearch, color: "text-blue-500", bg: "bg-blue-50", href: "/scout", status: "Ready" },
    { title: "Coach Agent", desc: "Skill Training", icon: Target, color: "text-emerald-500", bg: "bg-emerald-50", href: "/coach", status: "Ready" },
    { title: "Simulation", desc: "Interview Practice", icon: PlayCircle, color: "text-purple-500", bg: "bg-purple-50", href: "/simulation", status: "Ready" },
    { title: "Application", desc: "CV & Cover Letters", icon: Briefcase, color: "text-orange-500", bg: "bg-orange-50", href: "/application", status: "Ready" },
    { title: "Rights Agent", desc: "Contract Scanner", icon: Scale, color: "text-red-500", bg: "bg-red-50", href: "/rights", status: "Ready" },
    { title: "Benchmark", desc: "Salary Analysis", icon: Brain, color: "text-cyan-500", bg: "bg-cyan-50", href: "/benchmark", status: "Ready" }
  ]

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Welcome back</h1>
          <p className="text-muted-foreground mt-1">Here is the status of your AI career agents.</p>
        </div>
        <Button className="bg-cyan-600 hover:bg-cyan-700">
          Upload New CV <ArrowRight className="ml-2 h-4 w-4" />
        </Button>
      </div>

      {/* Stats Grid */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Average Match Score</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">78%</div>
            <p className="text-xs text-muted-foreground mt-1 text-emerald-600 flex items-center">
              <TrendingUp className="h-3 w-3 mr-1" /> +4% from last week
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Skills Mastered</CardTitle>
            <Target className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">12</div>
            <p className="text-xs text-muted-foreground mt-1">Via Coach Agent</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Applications Sent</CardTitle>
            <Briefcase className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">5</div>
            <p className="text-xs text-muted-foreground mt-1">Generated by AI</p>
          </CardContent>
        </Card>
      </div>

      {/* Agents Grid */}
      <div>
        <h2 className="text-xl font-semibold mb-4">Launch Agents</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {agents.map((agent, i) => (
            <Link key={i} href={agent.href}>
              <Card className="hover:shadow-md transition-all cursor-pointer h-full border-muted-foreground/20 hover:border-cyan-500/50">
                <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2">
                  <div className={`p-2 rounded-lg ${agent.bg}`}>
                    <agent.icon className={`h-5 w-5 ${agent.color}`} />
                  </div>
                  <div className="px-2 py-1 bg-zinc-100 text-zinc-600 rounded text-xs font-medium">
                    {agent.status}
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <CardTitle className="text-base">{agent.title}</CardTitle>
                  <CardDescription className="mt-1">{agent.desc}</CardDescription>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
